apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csuf-cpsc585-ai-bestmodelstorage
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi